image: "juliacomputing/juliapro:v1.4.1-3"

variables:
  JULIA_PKG_SERVER: juliateam.pumas.ai
  PRIVATE_REGISTRY_NAME: PumasRegistry
  PRIVATE_REGISTRY_UUID: 2207cf11-c0bb-4826-96c6-61cddfb0e7e8
  REMOVE_JULIAPRO: "true"

cache:
  paths:
    - $HOME/.julia/

build:
  stage: build
  script:
    - julia -e 'using InteractiveUtils;
                versioninfo()'
    - >
      julia --color=yes --project=. -e
      'using Pkg;
       Pkg.instantiate();
       using PumasTutorials;
       PumasTutorials.weave_file("introduction","introduction.jmd",
       (:script,:html,:notebook))'
  only:
  - master
  - tags
  - external
  - pushes

# deploy:
#   stage: deploy
#   script:
#     - julia -e 'using InteractiveUtils;
#                 versioninfo()'
#     - julia --color=yes --project -e 'using Pkg;
#                                       using PumasTutorials;
#                                       Pkg.activate(".");
#                                       Pkg.instantiate();'
#   only:
#   - master
#   - tags
#   - external
#   - pushes
